### ISSUE TITLE
Inbox example has extra scrollbar

### ISSUE THREAD

**Issue by jselden** [Availity/availity-uikit#109]
Trying to implement inbox type page. Having issue that seems to also be occuring on example page. 
The issue appears to be that entire page has scrollbar, where scolling is about the width of top nav.
This give weird behavior where scollbar for main-sidebar and main-content, and also on entire page.

**Comment by robmcguinness** [comment]
by adding `overflow: hidden` to `<body>` I was able to remove the scrollbar.  not sure if this is the best solution for IE :disappointed:

**Comment by robmcguinness** [comment]
223f989414edcc48577fba431e61fc001b514af0 fixes this

**Comment by robmcguinness** [comment]
### IE 11

![image](https://cloud.githubusercontent.com/assets/281070/10326352/1673cc52-6c4f-11e5-8419-ac8ec2649be4.png)

### IE 9

![image](https://cloud.githubusercontent.com/assets/281070/10326367/3cbaf494-6c4f-11e5-9121-7618fd27abf3.png)

**Comment by robmcguinness** [comment]
### IE9 Responsive

![image](https://cloud.githubusercontent.com/assets/281070/10326688/050b2678-6c53-11e5-8187-f78e1b47a950.png)
