### ISSUE TITLE
Datepicker popup doesn't display on IE8

### ISSUE THREAD

**Issue by danielspangler** [Availity/availity-uikit#11]
The datepicker doesn't popup on IE8.  The button displays but nothing happens when you click on it.

**Comment by robmcguinness** [comment]
It seems that datepicker included in the UIKit does not support IE8 without some polyfills.

+ https://github.com/Eonasdan/bootstrap-datetimepicker/blob/1b2fe6ef0062e17238117852f2c6b3ec2c2b0710/src/js/bootstrap-datetimepicker.js#L1238 == polyfill ==>  [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)
+ https://github.com/Eonasdan/bootstrap-datetimepicker/blob/1b2fe6ef0062e17238117852f2c6b3ec2c2b0710/src/js/bootstrap-datetimepicker.js#L986 == polyfill ==>  [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim)
+ https://github.com/Eonasdan/bootstrap-datetimepicker/blob/1b2fe6ef0062e17238117852f2c6b3ec2c2b0710/src/js/bootstrap-datetimepicker.js#L1375 == polyfill ==>  [indexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)

Even after I patched the lib with polyfills the *blur* event on the input field was causing the calendar to close prematurely.

We are investigating some options.

**Comment by robmcguinness** [comment]
Switched to [eternicode/bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) in [v0.4.0](https://github.com/Availity/availity-uikit/tree/v0.4.0)
