### ISSUE TITLE
checkbox-success / checkbox-info etc missing from availity-uikit.css

### ISSUE THREAD

**Issue by cornellb** [Availity/availity-uikit#110]
There are samples for checkboxes at
http://availity.github.io/availity-uikit/components.html#CheckboxesandRadios

Anyway, new prjs created using availity-uikit dont have these css classes in their availity-uikit.css.

**Comment by robmcguinness** [comment]
did you upgrade?

**Comment by cornellb** [comment]
I just did, it works now, I got in here to close the ticket and I saw your advise too. So it's good, just needed an update.

**Comment by robmcguinness** [comment]
:+1:
