### ISSUE TITLE
After bower-update, multi-select field doesnt work properly anymore (check mark not displayed)

### ISSUE THREAD

**Issue by cornellb** [Availity/availity-uikit#111]
The checkbox doesnt display the check mark when checked (the "edit" field below ie "Begin typing the organization name" shows up fine).

          
          <div>
            <div class="checkbox">
              <label>
                <input type="checkbox" data-ng-model="reg.orgsOn" value="">
                Organization(s)
              </label>
            </div>

            <div class="form-group" ng-show="reg.orgsOn">
              <select id="communicOrg" class="form-control select2" multiple data-av-dropdown="" data-ng-model="reg.selectedOrgs" data-ng-options="org.name for org in reg.orgs" data-ng-change="selectAction(reg.selectedOrgs)" data-placeholder="Begin typing the organization name" data-allow-clear="true">
                <option></option>
              </select>
            </div>
          </div>

**Comment by robmcguinness** [comment]
hmm...i see Angular code.  maybe this should be addressed in [availity-angular](https://github.com/Availity/availity-angular)?

**Comment by robmcguinness** [comment]
doesn't appear to be an issue.  please reopen if it is.
