### ISSUE TITLE
Checkbox/Radio pointer cursor hover issue

### ISSUE THREAD

**Issue by acouchman** [Availity/availity-uikit#116]
Looks like the 'cursor: pointer' is only firing for the very top and right sections of the checkboxes and radio buttons.  This can be observed in the UI-kit demo.

**Comment by JamieCrisman** [comment]
Doesn't seem to have `cursor: pointer` on the input itself?

**Comment by robmcguinness** [comment]
hmm...I don't see the issue or possibly misunderstanding it :neckbeard: can you drop a screenshot?

**Comment by JamieCrisman** [comment]
both should have pointer, but first one (which is more inside the box) is not
<img width="517" alt="leftside" src="https://cloud.githubusercontent.com/assets/697955/10900067/de5e1fb8-81a0-11e5-9772-7c9226a0fa8a.png">

<img width="528" alt="rightside" src="https://cloud.githubusercontent.com/assets/697955/10900068/de5f30ce-81a0-11e5-8b01-c89024850f70.png">

**Comment by robmcguinness** [comment]
hmm...same behavior with http://getbootstrap.com/css/#checkboxes-and-radios.  Seems expected behavior from browsers + Bootstrap.  

Thoughts?

**Comment by acouchman** [comment]
Ok, probably not worth dealing with on it on our side.  I'll just make QA aware this is a Bootstrap issue.  Close this issue?

**Comment by robmcguinness** [comment]
yes please :smile_cat:
