### ISSUE TITLE
require('availity-uikit') brings in the ES6 module

### ISSUE THREAD

**Issue by sgillespie** [Availity/availity-uikit#131]
`import 'availity-uikit` grabs the ES6 version when using npm and webpack

```
ERROR in ./~/availity-uikit/js/index.js
Module parse failed: /home/sgillespie/dev/repositories/availity-angular/node_modules/availity-uikit/js/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import './modal';
| 
| const availity = {
 @ ./~/availity-uikit/main.js 1:0-15
```

The workaround would be to either transpile that or `import 'availity-uikit/dist/availity-uikit.min.js';`

**Comment by TheSharpieOne** [comment]
Fixed in 3fdc9899
npm prepublish will create the lib directory which will contain individual transpiled files which can be included via the standard import/require process (package.json points to lib/index.js).
lib is only in the npm module, it is not committed to git.
