### ISSUE TITLE
card-inverse to set cards default color to card-text's

### ISSUE THREAD

**Issue by KaseyPowers** [Availity/availity-uikit#142]
I tend to make simple cards with `<div class="card card-block">` and some content inside without using .card-text or .card-title, if I try to use card-inverse with this pattern, the text does not change. 
![screen shot 2016-08-10 at 3 57 59 pm](https://cloud.githubusercontent.com/assets/4523739/17568794/46c773d8-5f13-11e6-94ba-011934dd37e3.png)

**Comment by robmcguinness** [comment]
is this still an issue in branch [feature/v3-fixes](https://github.com/Availity/availity-uikit/tree/feature/v3-fixes)?

**Comment by TheSharpieOne** [comment]
Bootstrap color/styles comes through.
```
.card-inverse {
    color: rgba(255, 255, 255, 0.65);
}
```
http://codepen.io/TheSharpieOne/pen/pRNQqg

Unfortunately, bootstrap 3 doesn't have cards out of the box, so the styles don't come through there. (Hint. hint, you are using uikit v2). This is already addressed in uikit v3, (unless we want v3 to look like v2 and have the dark text color). We should probably backport it to v2.
