### ISSUE TITLE
Use select2 v4 in uikit v3

### ISSUE THREAD

**Issue by paulirwin** [Availity/availity-uikit#144]
My reasoning for submitting this is actually somewhat strange... Select2 changed its npm package id from Select2 (note the capital letter) to select2 in the transition from 3.x to 4. UIKit v3 references v3.5, which conflicts case-wise if your project uses v4 since webpack requires case sensitive paths. But either way, it would be good to go ahead and get the upgrade over with for UIKit v3.

**Comment by TheSharpieOne** [comment]
We need to update from select v3 to select v4. Not sure what all is involved, select2 is only used in the [javascript example](http://availity.github.io/availity-uikit/v3.0.0-beta.2/pages/javascript/#select2) and for v3, it's broken.

We should also look towards making these JS opinionated libraries optional. For instance, if someone was using a library like React along with this uikit, then select2 would probably not be used (in fact none of the javascript this library has would probably be used), 'native' react components would usually be used instead.

**Comment by robmcguinness** [comment]
In `v1` and `v2` we included the Select2 `v3.5` css in order to support the `availity-angular` library but we can remove this dependency for `v3`.  I think `availit-uikit v3` should just be vanilla BS4.

**Comment by TheSharpieOne** [comment]
I think it is fine to identify and specify how a select should look and work/function (which happens to look like select2 and selectorizr's bootstrap theme as well as others) but leave it up to the user/dev to determine how implement it. We can suggest things such as select2, react-select, and various thing that work well with other popular libraries.

**Comment by robmcguinness** [comment]
can this be closed?
