### ISSUE TITLE
UIKit v3 trying to use the wrong path to the icon font file

### ISSUE THREAD

**Issue by paulirwin** [Availity/availity-uikit#145]
I _think_ this may be a UIKit issue, but it also could be a workflow issue.

The availity-icon-font is referenced as `fonts/availity-icon-font.*` in the generated CSS source. Workflow is building all of the CSS into a `css/vendor.css` file, so it's looking for `/css/fonts/availity-icon-font.*` which doesn't exist, so we get a 404 and the font icons are broken. 

If this is in fact a workflow v2 issue, let me know and I'll close this and reopen it there.

cc @robmcguinness

**Comment by TheSharpieOne** [comment]
add `$availity-font-path: '~availity-uikit/fonts';` to scss file before you import it like so:
```
$availity-font-path: '~availity-uikit/fonts';
@import '~availity-uikit/scss/bootstrap';
```

This is needed since it now uses scss instead of less

**Comment by paulirwin** [comment]
Alright so now that I'm past my Workflow issues, this works when I include Workflow as file:../availity-workflow but the icons do not work when I include Workflow as github:availity/availity-workflow#feature/v2. I think there might still be some kind of relative path issue going on. The icon fonts do correctly get put in my build/fonts folder by webpack, but the CSS is trying to reference them as /css/fonts/* instead of /fonts/* and it gets a 404.

**Comment by paulirwin** [comment]
... disregard my earlier comment (now deleted). This was because my local repo had the changes that need to go into the workflow feature/v2 branch. Submitting a PR now.

**Comment by paulirwin** [comment]
This works with the upstream workflow repo now as of https://github.com/Availity/availity-workflow/commit/85e175f3a187c33b9146e93f8db8b69ba123166b
