### ISSUE TITLE
Breaking change from Bootstrap 4

### ISSUE THREAD

**Issue by IndifferentDisdain** [Availity/availity-uikit#148]
https://github.com/twbs/bootstrap/commit/49153ecf4f1daa57c6f09e0cb01f7942cb7baf82

TL;DR: scss variable $grid-gutter-width was renamed to $grid-gutter-width-base, so the uikit _navbar.scss should be updated to use the new variable name. Sending PR your way.

Thanks,
Joe

**Comment by TheSharpieOne** [comment]
fixed via 5d5499ad7 (#149)
