### ISSUE TITLE
Bootstrap v4.0.0-alpha.6

### ISSUE THREAD

**Issue by sgillespie** [Availity/availity-uikit#154]
Bootstrap 4.0.0-alpha.6 appears to have broken the `feature/v3` branch. Take a look at the output of `npm start`:

```
[1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader?limit=32768?name=images/[name].[ext]!./~/postcss-loader!./~/sass-loader?sourceMap!./docs/scss/docs.scss
    Module build failed:
    $availity-zindex-secondary-fixed: ($zindex-navbar-fixed - 10) !default;
                                      ^
          Undefined variable: "$zindex-navbar-fixed".
          in /Users/sgillespie/dev/availity-uikit/scss/_variables.scss (line 522, column 36)
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader?limit=32768?name=images/[name].[ext]!./~/postcss-loader!./~/sass-loader?sourceMap!./scss/_bootstrap.scss
    Module build failed:
    $availity-zindex-secondary-fixed: ($zindex-navbar-fixed - 10) !default;
                                      ^
          Undefined variable: "$zindex-navbar-fixed".
          in /Users/sgillespie/dev/availity-uikit/scss/_variables.scss (line 522, column 36)
```

**Comment by sgillespie** [comment]
Even if we fix the issue above, `awesome-bootstrap-checkbox` probably also needs to be updated:

```
    ERROR in ./~/css-loader?limit=32768?name=images/[name].[ext]!./~/postcss-loader!./~/sass-loader?sourceMap!./scss/_bootstrap.scss
    Module build failed:

                  ^
          No mixin named tab-focus

    Backtrace:
        node_modules/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.scss:205
          in /Users/sgillespie/dev/availity-uikit/node_modules/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.scss (line 205, column 16)
```

**Comment by sgillespie** [comment]
https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/111

**Comment by TheSharpieOne** [comment]
i've been working on this when I get time since the release of beta 6. I'm mostly done, but need to fix some of the examples (mainly the navbars since they have completely changed). I should have something up soon.

**Comment by TheSharpieOne** [comment]
Just added [39bc05b]. This was a major change since flexbox in now the only display that is supported. This pretty much breaks all of the custom components and additions that were added by availity as they do not work well with the flexbox model. When v4 is fully released we should probably redo this from scratch.

**Comment by karolyi** [comment]
+1. waiting for the fix, subscribing until then.

**Comment by TheSharpieOne** [comment]
3.0.0-beta.4 was published on npm (and github) with the changes for support of alpha 6. Report any issues in a new ticket and I'll resolve them in a timely manner.
