### ISSUE TITLE
Fix for Bootstrap 4 

### ISSUE THREAD

**Issue by IndifferentDisdain** [Availity/availity-uikit#162]
Any way the BS4 issue below could be addressed in a version of uikit? We were hoping a beta or another alpha of BS4 would be out by now that addressed it, but no such luck thus far.

https://github.com/twbs/bootstrap/issues/21651

Thanks,
Joe

**Comment by TheSharpieOne** [comment]
Current workaround is to add `.flex-row` to the input.

**Comment by IndifferentDisdain** [comment]
That is awesome; thanks!
