### ISSUE TITLE
Update Colors for Accessibility

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#167]
- green `#157461`
- gray `#676971`

**Comment by TheSharpieOne** [comment]
This has been merged into `v3` via ba8b934, `v2` is still needed.

**Comment by KaseyPowers** [comment]
More details:

- Remove all use of `#7e8188` and `#81878b` replace with gray mentioned earlier `#676971`
- `.text-muted` might be using the bad gray
- Change warning text (`.text-warning` and in forms) to have correct contrast. Bootstrap default has `#8a6d3b`
- Increase loading indicaor size (Testing 3.5em) and make sure it has correct green.
-

**Comment by christieb7007** [comment]
- `.text-muted` : `#66686d` (lighten 10% instead of 20%)
- `$orange` : `#ed5624` --> `#d93d11`
- `$secondary-blue` : `#0093e8` --> `#007CC2`
- header-links lighten 15% instead of 20%

I can make PR to v3 if this looks good

**Comment by robmcguinness** [comment]
Closing. @christieb7007 fixed most of the issues in `v3`. I''l open another issue for `v2`
