### ISSUE TITLE
Add new icons from v1 into v2/v3

### ISSUE THREAD

**Issue by derekonay** [Availity/availity-uikit#169]
New icons were added in the v1.2.2-v1.2.5 of Availity UI-Kit. To keep consistency across the versions where possible, we will want to go back and include the following additional icons in the latest versions:
- icon-paper-plane
- icon-paper-plane-empty
- icon-hourglass-2 
- icon-camera

The config file below already includes the frown, smile, and meh icons that were added solely to v2.

**Comment by robmcguinness** [comment]
attach the icon config file here so we can apply to `v2` and `v3`

**Comment by derekonay** [comment]
Github doesn't support JSON upload, so I threw the config.json file in the following ZIP:
[Font Configuration File](https://github.com/Availity/availity-uikit/files/1084951/config.zip)

**Comment by robmcguinness** [comment]
muchas gracias

**Comment by robmcguinness** [comment]
closing. please open a PR if those icons are needed in `v2` or `v3`.
