### ISSUE TITLE
Pills are not changing active tab

### ISSUE THREAD

**Issue by christieb7007** [Availity/availity-uikit#188]
Pills and secondary pills are not changing active states and text
![image](https://user-images.githubusercontent.com/12239092/32845731-1f291162-c9eb-11e7-8b7b-3f25014197c5.png)

**Comment by TheSharpieOne** [comment]
This is working for me. Are you seeing any errors in your console?

Note: This is just using bootstrap's jquery-based javascript for the examples.

**Comment by christieb7007** [comment]
I am running v3 locally and there are no errors in console...does the mega menu work for you?

**Comment by TheSharpieOne** [comment]
locally is probably the key. I was just checking on the docs site.

**Comment by robmcguinness** [comment]
@TheSharpieOne the docs locally are using Gatsby now and `jquery` is not setup yet.

**Comment by TheSharpieOne** [comment]
Can we leverage reactstrap? (and if not for the examples, then at least for the site components themselves)

**Comment by robmcguinness** [comment]
@TheSharpieOne Yes we can. I was hoping to keep the Boostrap examples pure.
