### ISSUE TITLE
Buttons: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#193]
![image](https://user-images.githubusercontent.com/281070/32983115-cd581336-cc5d-11e7-92c7-4c60dbb083ef.png)

![image](https://user-images.githubusercontent.com/281070/32983117-d206c648-cc5d-11e7-8ebb-eb27250eae35.png)

**Comment by christieb7007** [comment]
![image](https://user-images.githubusercontent.com/12239092/33079780-0ebda29c-ce9c-11e7-99d4-90362e4cc753.png)
