### ISSUE TITLE
Forms: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#196]
![image](https://user-images.githubusercontent.com/281070/32983142-505183a8-cc5e-11e7-827b-55f50956268f.png)

![image](https://user-images.githubusercontent.com/281070/32983146-571bf54c-cc5e-11e7-9450-63bb050b9b89.png)

![image](https://user-images.githubusercontent.com/281070/32983149-65544d80-cc5e-11e7-96cf-bb73403fc37c.png)

![image](https://user-images.githubusercontent.com/281070/32983151-6d22c69a-cc5e-11e7-8b21-2db58a5f7b24.png)

![image](https://user-images.githubusercontent.com/281070/32983152-728d645a-cc5e-11e7-9d7f-6f885a29009e.png)

![image](https://user-images.githubusercontent.com/281070/32983154-778000f8-cc5e-11e7-8b85-323a80f0432d.png)

**Comment by christieb7007** [comment]
https://github.com/Availity/availity-uikit/pull/203
