### ISSUE TITLE
Headers: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#198]
![image](https://user-images.githubusercontent.com/281070/32983171-b786cdbc-cc5e-11e7-8815-c43f39c5be3d.png)

![image](https://user-images.githubusercontent.com/281070/32983172-c27c94ae-cc5e-11e7-83fc-1c338b567b4b.png)

![image](https://user-images.githubusercontent.com/281070/32983174-c73f8f00-cc5e-11e7-9379-f7ea8d52f27a.png)

![image](https://user-images.githubusercontent.com/281070/32983179-d99d9af2-cc5e-11e7-80ca-2e98080245fd.png)

![image](https://user-images.githubusercontent.com/281070/32983182-ddaff4b4-cc5e-11e7-9b04-46a66d78910e.png)

**Comment by christieb7007** [comment]
header link fixed with PR https://github.com/Availity/availity-uikit/pull/203
icon colors fixed with PR https://github.com/Availity/availity-uikit/pull/204
