### ISSUE TITLE
Pagination: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#200]
![image](https://user-images.githubusercontent.com/281070/32983246-875ecb7a-cc5f-11e7-9834-19dc528dabd3.png)

![image](https://user-images.githubusercontent.com/281070/32983248-8ec29fc2-cc5f-11e7-9c4a-2e0e53b708da.png)

**Comment by christieb7007** [comment]
Non-issue - the contrast is 7.72
![image](https://user-images.githubusercontent.com/12239092/33096292-1741030c-cecc-11e7-9505-01ec5e53fd57.png)

![image](https://user-images.githubusercontent.com/12239092/33096249-f5cd3506-cecb-11e7-82b5-533f0f2216bb.png)
