### ISSUE TITLE
Progress Bar Contextual Bug

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#216]
Progress bar defaults override contextual variants

![image](https://user-images.githubusercontent.com/281070/35053763-01b702dc-fb79-11e7-9395-cc4ab71fba34.png)

In the example above `.progress-bar-danger` should draw red progress bar

**Comment by robmcguinness** [comment]
fixed in `v1` ea960209e595a01ef042b60c296fedba5e59bded

**Comment by christieb7007** [comment]
`bs4` classes for v3 are `bg-success` and `bg-danger`
