### ISSUE TITLE
Suppress text-hide warning from BS4.1

### ISSUE THREAD

**Issue by robmcguinness** [Availity/availity-uikit#227]
https://github.com/twbs/bootstrap/issues/26237

```
.text-hide {
  @include text-hide();	  @include text-hide($ignore-warning: true);
}
```

**Comment by TheSharpieOne** [comment]
There is no action we can take since this is coming directly from bootstrap, we cannot replace the reference since it is not in our code.
The issue has been fixed upstream and will be in the next bootstrap release.

**Comment by robmcguinness** [comment]
ok sounds good.
