### ISSUE TITLE
Adding bg theme for light green? 

### ISSUE THREAD

**Issue by KaseyPowers** [Availity/availity-uikit#239]
I've needed to set up a card with light green similar to a valid form or success row in a context table. 

What are thoughts on this? 
I use `bg-help` but could also see `bg-success-light`

**Comment by KaseyPowers** [comment]
![screen shot 2018-07-10 at 10 51 13 am](https://user-images.githubusercontent.com/4523739/42520120-811d4a16-8433-11e8-9289-3edb6ec108e5.png)
example of my card, don't see the exact green in our variables but could use something similar I'm sure

**Comment by derekonay** [comment]
I don't know if it's the color you are using but they look like the light variant of our green color. I found them on the master branch:
- https://github.com/Availity/availity-uikit/blob/master/less/variables.less#L29
