### ISSUE TITLE
Publish Updated Docs

### ISSUE THREAD

**Issue by TheSharpieOne** [Availity/availity-uikit#275]
Docs (gh-pages branch) haven't been updated in 3 years! It has v3 as the latest. v4 was released a bit ago.
I am not sure if there is another place for updated docs, but the links still go to https://availity.github.io/availity-uikit/ which has v3.1 as the latest.

**Comment by robmcguinness** [comment]
I believe this is purely because of the lack of automation in the release process for this project. I think the `4.0` release turned out to be minor changes and the current docs still reflect the correct UI style guidelines for projects based on Bootstrap `v4`.
