### ISSUE TITLE
Unable to Create React App using Availity command npx @availity/workflow init workflow-app

### ISSUE THREAD

**Issue by Ravikiranmp1023672** [Availity/availity-uikit#279]
Hi Team, 
I am trying to create a React app using the command npx @availity/workflow init workflow-app
but getting error as GIT is not internal command and aborting installation, please find the attached screenshot for the reference

![image](
![image](https://user-images.githubusercontent.com/85186821/120419392-37a29c80-c317-11eb-923f-852697c15e91.png)

**Comment by chrishavekost** [comment]
This seems to be an issue with `git` not being properly set up, not an issue with the UI kit.
