### ISSUE TITLE
List group inner hamburger menu

### ISSUE THREAD

**Issue by nickolaswilson** [Availity/availity-uikit#57]
Having inner <li><a></a></li> tags under a list-group results in distorted UI. (Rows are created for the inner anchor tags)
One way around this is to exchange the <a></a> tags with <span></span> and replicating the CSS of the anchor tag for the spans.

This would happen with code such as below:
```js
<div class="list-group list-group-cards">
  <div ng-repeat="form in forms">
    <a class="list-group-item">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          <span class="icon icon-menu"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a>Delete</a></li>
          <li><a>View as PDF</a></li>
         </ul>
       </div>
     </div>
   </a>
 </div>
</div>

```

**Comment by bobbennett** [comment]
I'm guessing the bad behavior is being caused by nesting anchors tags which is not valid HTML. Try swapping your .list-group-item anchor with a div. Then add .list-group-selectable to your .list-group in order to preserve the cursors and colors.

**Comment by nickolaswilson** [comment]
I had tried that with the default list-group class, but it didn't have the same hover classes, I'll give it a shot with list-group-selectable tomorrow thanks.
