### ISSUE TITLE
Add link to Select2

### ISSUE THREAD

**Issue by ammerritt** [Availity/availity-uikit#72]
In "Do not use HTML's select tag. Instead, see the Select2 section on the JavaScript tab for proper examples for selection widgets." from: http://availity.github.io/availity-uikit/components.html#Select  Can you make Select2 that a link so I don't have to go look for it?

**Comment by bobbennett** [comment]
A link was added, but it's a broken link. Sends you to http://availity.github.io/javascript.html#Select2 instead of http://availity.github.io/availity-uikit/javascript.html#Select2.

The javascript link has the same issue.

**Comment by robmcguinness** [comment]
can you review?
