### ISSUE TITLE
.btn-file hover supersedes other btn classes

### ISSUE THREAD

**Issue by bobbennett** [Availity/availity-uikit#77]
.btn-file does not work well in conjunction with other btn color classes.

![image](https://cloud.githubusercontent.com/assets/902065/8817854/d000a8e6-3006-11e5-875c-e74d7422ab00.png)

**Comment by robmcguinness** [comment]
I don't think `btn-file` intent was to effect the other classes since there is only 1 style for file buttons (it used to be but it was removed)  can you check with UX?

**Comment by bobbennett** [comment]
I figured it wasn't the intent, so the fix is already merged in. I referenced the issue in the pull request, but forgot to close out the issue.
