### ISSUE TITLE
vertical progress wizard text alignment

### ISSUE THREAD

**Issue by JamieCrisman** [Availity/availity-uikit#82]
## What it's doing
![progresswiz](https://cloud.githubusercontent.com/assets/697955/8990662/6df44df6-36b9-11e5-8f0d-d76b9e355cc2.PNG)

## What would be nice
![expectedprogresswiz](https://cloud.githubusercontent.com/assets/697955/8990798/363a7b78-36ba-11e5-91c4-47288f5e3410.PNG)

**Comment by robmcguinness** [comment]
inactive so closing
