### ISSUE TITLE
hover styles not applied to list group items under a list-group-selectable container

### ISSUE THREAD

**Issue by dnoler** [Availity/availity-uikit#89]
Looks like there is a slight issue with the LESS for applying hover styles to list group items under a list group selectable container. Only items with an "active" class are targetted for hover, I'm guessing due to a typo (curly braces set incorrectly).

**Comment by JamieCrisman** [comment]
> I'm guessing due to a typo (curly braces set incorrectly).
could you link to the line?

**Comment by dnoler** [comment]
> could you link to the line?

I looked a bit further, I'm not quite sure what the goal was with the hover styles on active group items, so I didn't mess with those styles. I added the hover styles for all items under a selectable container. I also added an example and reworked the spacing in the LESS files so its more readable. I haven't been able to test the changes yet as I'm having trouble getting gulp working ATM.

https://github.com/Availity/availity-uikit/commit/8cba7af091ffdedaed6e5b09427426d457e88647

**Comment by bobbennett** [comment]
It looks like the braces are unintentionally misplaced. Most likely one is missing from the active class. The hover border should apply to active and non active list-group-items.

**Comment by dnoler** [comment]
Thanks Bobby. What about the list-group-item-text color? Is that also for both active and non-active?

**Comment by bobbennett** [comment]
I believe so. the initial intent was to a) provide the hover effects when not using anchors for list group items and b) override the blue bg with white text when an item is selected.

**Comment by dnoler** [comment]
Got it. I'll make the necessary adjustments.
