### ISSUE TITLE
Title wrapping in headers

### ISSUE THREAD

**Issue by SpoonsWithWolves** [Availity/availity-uikit#97]
Headers are wrapping prematurely when there is still space available in the container.  

What it does:
![screen shot 2015-09-02 at 2 41 47 pm](https://cloud.githubusercontent.com/assets/8885120/9642383/d282f62e-5189-11e5-9804-c7b2940c8931.png)

What we'd like it to do:
![screen shot 2015-09-02 at 2 42 45 pm](https://cloud.githubusercontent.com/assets/8885120/9642402/f8e9630c-5189-11e5-9587-4319ebe84c52.png)

**Comment by robmcguinness** [comment]
hmm...i don't think we do anything special for text.  the browser should be wrapping the text with the appropriate space.  in your second example did you modify the css to achieve the effect?
